# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_image3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1441, 944)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("QMainWindow {background-color:white}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(20, 10, 200, 861))
        self.toolBox.setMinimumSize(QtCore.QSize(200, 2))
        self.toolBox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("QToolBox {\n"
"    background-color: #f2f2f2;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"}\n"
"QToolBox::tab {\n"
"    background-color: #e0e0e0;\n"
"    color: #013B89;\n"
"    padding: 5px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    background-color: #013B89;\n"
"    color: #fff;\n"
"}\n"
"QWidget#page{\n"
"  background: white\n"
"}\n"
"QWidget#page_2{\n"
"  background: white\n"
"}\n"
"QWidget#page_3{\n"
"  background: white\n"
"}")
        self.toolBox.setLineWidth(1)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 198, 772))
        self.page.setObjectName("page")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 280, 91, 31))
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border-top-left-radius: 10px; \n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px; \n"
"    border-bottom-right-radius: 10px;\n"
"    background:rgb(1,59,137);   /*背景颜色*/\n"
"    color:white;   /*字体颜色*/\n"
"}\n"
"          /*鼠标指向按钮后按钮变化*/\n"
"QPushButton:hover{\n"
"    color:#F5F5F5;\n"
"    background:rgb(247,165,1);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 240, 91, 31))
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_3.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border-top-left-radius: 10px; \n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px; \n"
"    border-bottom-right-radius: 10px;\n"
"    background:rgb(1,59,137);   /*背景颜色*/\n"
"    color:white;   /*字体颜色*/\n"
"}\n"
"          /*鼠标指向按钮后按钮变化*/\n"
"QPushButton:hover{\n"
"    color:#F5F5F5;\n"
"    background:rgb(247,165,1);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.page)
        self.pushButton_4.setGeometry(QtCore.QRect(21, 730, 151, 28))
        self.pushButton_4.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_4.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border-top-left-radius: 10px; \n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px; \n"
"    border-bottom-right-radius: 10px;\n"
"    background:rgb(1,65,137);   /*背景颜色*/\n"
"    color:white;   /*字体颜色*/\n"
"}\n"
"          /*鼠标指向按钮后按钮变化*/\n"
"QPushButton:hover{\n"
"    color:#F5F5F5;\n"
"    background:rgb(247,165,1);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.page)
        self.pushButton_5.setGeometry(QtCore.QRect(19, 380, 151, 28))
        self.pushButton_5.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border-top-left-radius: 10px; \n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px; \n"
"    border-bottom-right-radius: 10px;\n"
"    background:rgb(1,59,137);   /*背景颜色*/\n"
"    color:white;   /*字体颜色*/\n"
"}\n"
"          /*鼠标指向按钮后按钮变化*/\n"
"QPushButton:hover{\n"
"    color:#F5F5F5;\n"
"    background:rgb(247,165,1);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.page)
        self.pushButton_7.setGeometry(QtCore.QRect(19, 480, 151, 28))
        self.pushButton_7.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    border-top-left-radius: 10px; \n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px; \n"
"    border-bottom-right-radius: 10px;\n"
"    background:rgb(1,65,137);   /*背景颜色*/\n"
"    color:white;   /*字体颜色*/\n"
"}\n"
"          /*鼠标指向按钮后按钮变化*/\n"
"QPushButton:hover{\n"
"    color:#F5F5F5;\n"
"    background:rgb(247,165,1);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.page)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 580, 151, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    border-top-left-radius: 10px; \n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px; \n"
"    border-bottom-right-radius: 10px;\n"
"    background:rgb(1,65,137);   /*背景颜色*/\n"
"    color:white;   /*字体颜色*/\n"
"}\n"
"          /*鼠标指向按钮后按钮变化*/\n"
"QPushButton:hover{\n"
"    color:#F5F5F5;\n"
"    background:rgb(247,165,1);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(30, 140, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    color: #014189;\n"
" \n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: transparent;\n"
"    border-radius: 0px;\n"
"\n"
"    background-color: transparent;\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(30, 180, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    color: #014189;\n"
" \n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: transparent;\n"
"    border-radius: 0px;\n"
"\n"
"    background-color: transparent;\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(10, 620, 181, 20))
        self.label.setStyleSheet("QLabel {\n"
"    color: #014189;\n"
" \n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: transparent;\n"
"    border-radius: 0px;\n"
"\n"
"    background-color: transparent;\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(10, 210, 181, 20))
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #014189;\n"
" \n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: transparent;\n"
"    border-radius: 0px;\n"
"\n"
"    background-color: transparent;\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"    color: #014189;\n"
" \n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: transparent;\n"
"    border-radius: 0px;\n"
"\n"
"    background-color: transparent;\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.date = QtWidgets.QLineEdit(self.page)
        self.date.setGeometry(QtCore.QRect(70, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.date.setFont(font)
        self.date.setObjectName("date")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(20, 50, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-radius:10px;  /* 按钮圆角 2个像素 */\n"
"    background:rgb(1,65,137);   /*背景颜色*/\n"
"    color:white;   /*字体颜色*/\n"
"}\n"
"          /*鼠标指向按钮后按钮变化*/\n"
"QPushButton:hover{\n"
"    color:#F5F5F5;\n"
"    background:rgb(247,165,1);\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.code_box = QtWidgets.QComboBox(self.page)
        self.code_box.setGeometry(QtCore.QRect(10, 240, 71, 31))
        self.code_box.setMinimumSize(QtCore.QSize(0, 0))
        self.code_box.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.code_box.setFont(font)
        self.code_box.setStyleSheet("QComboBox QAbstractItemView {\n"
"    selection-background-color: #013B89;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    text-align: AlignHCenter;\n"
"    border: 1px white;\n"
"    outline: 0px;\n"
"}\n"
"QComboBox:hover {\n"
"    color: rgb(247,165,1);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.code_box.setObjectName("code_box")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.code_box.addItem("")
        self.close_code = QtWidgets.QComboBox(self.page)
        self.close_code.setGeometry(QtCore.QRect(20, 340, 151, 31))
        self.close_code.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.close_code.setFont(font)
        self.close_code.setStyleSheet("QComboBox QAbstractItemView {\n"
"    selection-background-color: #013B89;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    text-align: AlignHCenter;\n"
"    border: 1px white;\n"
"    outline: 0px;\n"
"}\n"
"QComboBox:hover {\n"
"    color: rgb(247,165,1);\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.close_code.setObjectName("close_code")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_code.addItem("")
        self.close_spread_box = QtWidgets.QComboBox(self.page)
        self.close_spread_box.setGeometry(QtCore.QRect(20, 440, 151, 31))
        self.close_spread_box.setMinimumSize(QtCore.QSize(80, 0))
        self.close_spread_box.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.close_spread_box.setFont(font)
        self.close_spread_box.setStyleSheet("QComboBox QAbstractItemView {\n"
"    selection-background-color: #013B89;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    text-align: AlignHCenter;\n"
"    border: 1px white;\n"
"    outline: 0px;\n"
"}\n"
"QComboBox:hover {\n"
"    color: rgb(247,165,1);\n"
"    background-color: transparent;\n"
"}")
        self.close_spread_box.setObjectName("close_spread_box")
        self.close_spread_box.addItem("")
        self.close_spread_box.addItem("")
        self.close_spread_box.addItem("")
        self.close_spread_box.addItem("")
        self.close_spread_box.addItem("")
        self.close_spread_box.addItem("")
        self.close_spread_box.addItem("")
        self.close_spread_box.addItem("")
        self.close_spread_box.addItem("")
        self.close_spread_box.addItem("")
        self.term_box = QtWidgets.QComboBox(self.page)
        self.term_box.setGeometry(QtCore.QRect(10, 280, 71, 31))
        self.term_box.setMinimumSize(QtCore.QSize(0, 0))
        self.term_box.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.term_box.setFont(font)
        self.term_box.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.term_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.term_box.setStyleSheet("QComboBox QAbstractItemView {\n"
"    selection-background-color: #013B89;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    text-align: AlignHCenter;\n"
"    border: 1px white;\n"
"    outline: 0px;\n"
"}\n"
"QComboBox:hover {\n"
"    color: rgb(247,165,1);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"")
        self.term_box.setObjectName("term_box")
        self.term_box.addItem("")
        self.term_box.addItem("")
        self.term_box.addItem("")
        self.term_box.addItem("")
        self.term_box.addItem("")
        self.term_box.addItem("")
        self.term_box.addItem("")
        self.m_box = QtWidgets.QComboBox(self.page)
        self.m_box.setGeometry(QtCore.QRect(20, 540, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.m_box.setFont(font)
        self.m_box.setStyleSheet("QComboBox QAbstractItemView {\n"
"    selection-background-color: #013B89;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    text-align: AlignHCenter;\n"
"    border: 1px white;\n"
"    outline: 0px;\n"
"}\n"
"QComboBox:hover {\n"
"    color: rgb(247,165,1);\n"
"    background-color: transparent;\n"
"}")
        self.m_box.setObjectName("m_box")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.m_box.addItem("")
        self.axis_box = QtWidgets.QComboBox(self.page)
        self.axis_box.setGeometry(QtCore.QRect(110, 100, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.axis_box.setFont(font)
        self.axis_box.setStyleSheet("QComboBox QAbstractItemView {\n"
"    selection-background-color: #013B89;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    text-align: AlignHCenter;\n"
"    border: 1px white;\n"
"    outline: 0px;\n"
"}\n"
"QComboBox:hover {\n"
"    color: rgb(247,165,1);\n"
"    background-color: transparent;\n"
"}")
        self.axis_box.setObjectName("axis_box")
        self.axis_box.addItem("")
        self.axis_box.addItem("")
        self.axis_box.addItem("")
        self.axis_box.addItem("")
        self.b_n_box = QtWidgets.QComboBox(self.page)
        self.b_n_box.setGeometry(QtCore.QRect(110, 180, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.b_n_box.setFont(font)
        self.b_n_box.setStyleSheet("QComboBox QAbstractItemView {\n"
"    selection-background-color: #013B89;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    text-align: AlignHCenter;\n"
"    border: 1px white;\n"
"    outline: 0px;\n"
"}\n"
"QComboBox:hover {\n"
"    color: rgb(247,165,1);\n"
"    background-color: transparent;\n"
"}")
        self.b_n_box.setMinimumContentsLength(0)
        self.b_n_box.setObjectName("b_n_box")
        self.b_n_box.addItem("")
        self.b_n_box.addItem("")
        self.b_n_box.addItem("")
        self.b_n_box.addItem("")
        self.b_n_box.addItem("")
        self.b_n0_box = QtWidgets.QComboBox(self.page)
        self.b_n0_box.setGeometry(QtCore.QRect(110, 140, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.b_n0_box.setFont(font)
        self.b_n0_box.setStyleSheet("QComboBox QAbstractItemView {\n"
"    selection-background-color: #013B89;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    text-align: AlignHCenter;\n"
"    border: 1px white;\n"
"    outline: 0px;\n"
"}\n"
"QComboBox:hover {\n"
"    color: rgb(247,165,1);\n"
"    background-color: transparent;\n"
"}")
        self.b_n0_box.setObjectName("b_n0_box")
        self.b_n0_box.addItem("")
        self.b_n0_box.addItem("")
        self.b_n0_box.addItem("")
        self.b_n0_box.addItem("")
        self.layoutWidget = QtWidgets.QWidget(self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 680, 182, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vol_code = QtWidgets.QComboBox(self.layoutWidget)
        self.vol_code.setMinimumSize(QtCore.QSize(0, 30))
        self.vol_code.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.vol_code.setFont(font)
        self.vol_code.setStyleSheet("QComboBox QAbstractItemView {\n"
"    selection-background-color: #013B89;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    text-align: AlignHCenter;\n"
"    border: 1px white;\n"
"    outline: 0px;\n"
"}\n"
"QComboBox:hover {\n"
"    color: rgb(247,165,1);\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.vol_code.setObjectName("vol_code")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.vol_code.addItem("")
        self.horizontalLayout.addWidget(self.vol_code)
        self.w_box = QtWidgets.QComboBox(self.layoutWidget)
        self.w_box.setMinimumSize(QtCore.QSize(0, 30))
        self.w_box.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.w_box.setFont(font)
        self.w_box.setStyleSheet("QComboBox QAbstractItemView {\n"
"    selection-background-color: #013B89;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    text-align: AlignHCenter;\n"
"    border: 1px white;\n"
"    outline: 0px;\n"
"}\n"
"QComboBox:hover {\n"
"    color: rgb(247,165,1);\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.w_box.setObjectName("w_box")
        self.w_box.addItem("")
        self.w_box.addItem("")
        self.w_box.addItem("")
        self.w_box.addItem("")
        self.w_box.addItem("")
        self.w_box.addItem("")
        self.horizontalLayout.addWidget(self.w_box)
        self.layoutWidget1 = QtWidgets.QWidget(self.page)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 650, 181, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    color: #014189;\n"
" \n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: transparent;\n"
"    border-radius: 0px;\n"
"\n"
"    background-color: transparent;\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    color: #014189;\n"
" \n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: transparent;\n"
"    border-radius: 0px;\n"
"\n"
"    background-color: transparent;\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(20, 100, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: #014189;\n"
" \n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: transparent;\n"
"    border-radius: 0px;\n"
"\n"
"    background-color: transparent;\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.toolBox.addItem(self.page, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 198, 772))
        self.page_3.setObjectName("page_3")
        self.toolBox.addItem(self.page_3, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 198, 772))
        self.page_2.setObjectName("page_2")
        self.textEdit = QtWidgets.QTextEdit(self.page_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 181, 621))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.toolBox.addItem(self.page_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1441, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(2)
        self.b_n_box.setCurrentIndex(1)
        self.b_n0_box.setCurrentIndex(1)
        self.pushButton.clicked['bool'].connect(MainWindow.read_table) # type: ignore
        self.pushButton_2.clicked['bool'].connect(MainWindow.get_plot) # type: ignore
        self.term_box.currentTextChanged['QString'].connect(MainWindow.term_code_change) # type: ignore
        self.axis_box.currentTextChanged['QString'].connect(MainWindow.b_axis_change) # type: ignore
        self.code_box.currentTextChanged['QString'].connect(MainWindow.b_code_change) # type: ignore
        self.b_n0_box.currentIndexChanged['int'].connect(MainWindow.b_n0_change) # type: ignore
        self.b_n_box.currentIndexChanged['int'].connect(MainWindow.b_n_change) # type: ignore
        self.pushButton_3.clicked['bool'].connect(MainWindow.get_basis_plot) # type: ignore
        self.pushButton_4.clicked['bool'].connect(MainWindow.get_sigma) # type: ignore
        self.vol_code.currentTextChanged['QString'].connect(MainWindow.vol_code_change) # type: ignore
        self.pushButton_5.clicked['bool'].connect(MainWindow.get_close) # type: ignore
        self.close_code.currentTextChanged['QString'].connect(MainWindow.close_code_change) # type: ignore
        self.close_spread_box.currentTextChanged['QString'].connect(MainWindow.spread_change) # type: ignore
        self.pushButton_7.clicked['bool'].connect(MainWindow.close_spread) # type: ignore
        self.w_box.currentTextChanged['QString'].connect(MainWindow.window_change) # type: ignore
        self.pushButton_8.clicked['bool'].connect(MainWindow.get_m_plot) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setProperty("role", _translate("MainWindow", "axis"))
        self.pushButton_2.setText(_translate("MainWindow", "期限结构"))
        self.pushButton_3.setText(_translate("MainWindow", "基差"))
        self.pushButton_4.setText(_translate("MainWindow", "波动率季节性"))
        self.pushButton_5.setText(_translate("MainWindow", "收盘价季节性"))
        self.pushButton_7.setText(_translate("MainWindow", "品种价差季节性"))
        self.pushButton_8.setText(_translate("MainWindow", "月差季节性"))
        self.label_7.setText(_translate("MainWindow", "n0 值"))
        self.label_8.setText(_translate("MainWindow", "n值"))
        self.label.setText(_translate("MainWindow", "----------------------"))
        self.label_2.setText(_translate("MainWindow", "----------------------"))
        self.label_10.setText(_translate("MainWindow", "Date"))
        self.date.setText(_translate("MainWindow", "2023-12-29"))
        self.pushButton.setText(_translate("MainWindow", "连接"))
        self.code_box.setItemText(0, _translate("MainWindow", "M01"))
        self.code_box.setItemText(1, _translate("MainWindow", "M05"))
        self.code_box.setItemText(2, _translate("MainWindow", "M09"))
        self.code_box.setItemText(3, _translate("MainWindow", "RM01"))
        self.code_box.setItemText(4, _translate("MainWindow", "RM05"))
        self.code_box.setItemText(5, _translate("MainWindow", "RM09"))
        self.code_box.setItemText(6, _translate("MainWindow", "Y01"))
        self.code_box.setItemText(7, _translate("MainWindow", "Y05"))
        self.code_box.setItemText(8, _translate("MainWindow", "Y09"))
        self.code_box.setItemText(9, _translate("MainWindow", "P01"))
        self.code_box.setItemText(10, _translate("MainWindow", "P05"))
        self.code_box.setItemText(11, _translate("MainWindow", "P09"))
        self.code_box.setItemText(12, _translate("MainWindow", "OI01"))
        self.code_box.setItemText(13, _translate("MainWindow", "OI05"))
        self.code_box.setItemText(14, _translate("MainWindow", "OI09"))
        self.code_box.setItemText(15, _translate("MainWindow", "C03"))
        self.code_box.setItemText(16, _translate("MainWindow", "C05"))
        self.code_box.setItemText(17, _translate("MainWindow", "C07"))
        self.code_box.setItemText(18, _translate("MainWindow", "CS03"))
        self.code_box.setItemText(19, _translate("MainWindow", "CS05"))
        self.code_box.setItemText(20, _translate("MainWindow", "CS07"))
        self.close_code.setItemText(0, _translate("MainWindow", "M01M.DCE"))
        self.close_code.setItemText(1, _translate("MainWindow", "M05M.DCE"))
        self.close_code.setItemText(2, _translate("MainWindow", "M09M.DCE"))
        self.close_code.setItemText(3, _translate("MainWindow", "RM01M.CZC"))
        self.close_code.setItemText(4, _translate("MainWindow", "RM05M.CZC"))
        self.close_code.setItemText(5, _translate("MainWindow", "RM09M.CZC"))
        self.close_code.setItemText(6, _translate("MainWindow", "Y01M.DCE"))
        self.close_code.setItemText(7, _translate("MainWindow", "Y05M.DCE"))
        self.close_code.setItemText(8, _translate("MainWindow", "Y09M.DCE"))
        self.close_code.setItemText(9, _translate("MainWindow", "P01M.DCE"))
        self.close_code.setItemText(10, _translate("MainWindow", "P05M.DCE"))
        self.close_code.setItemText(11, _translate("MainWindow", "P09M.DCE"))
        self.close_code.setItemText(12, _translate("MainWindow", "OI01M.CZC"))
        self.close_code.setItemText(13, _translate("MainWindow", "OI05M.CZC"))
        self.close_code.setItemText(14, _translate("MainWindow", "OI09M.CZC"))
        self.close_code.setItemText(15, _translate("MainWindow", "C03M.DCE"))
        self.close_code.setItemText(16, _translate("MainWindow", "C05M.DCE"))
        self.close_code.setItemText(17, _translate("MainWindow", "C07M.DCE"))
        self.close_code.setItemText(18, _translate("MainWindow", "CS03M.DCE"))
        self.close_code.setItemText(19, _translate("MainWindow", "CS05M.DCE"))
        self.close_code.setItemText(20, _translate("MainWindow", "CS07M.DCE"))
        self.close_spread_box.setItemText(0, _translate("MainWindow", "Y&P&OI 05"))
        self.close_spread_box.setItemText(1, _translate("MainWindow", "M&RM 05"))
        self.close_spread_box.setItemText(2, _translate("MainWindow", "CS&C 05"))
        self.close_spread_box.setItemText(3, _translate("MainWindow", "Y/M 05"))
        self.close_spread_box.setItemText(4, _translate("MainWindow", "OI/RM 05"))
        self.close_spread_box.setItemText(5, _translate("MainWindow", "Y&P&OI 09"))
        self.close_spread_box.setItemText(6, _translate("MainWindow", "M&RM 09"))
        self.close_spread_box.setItemText(7, _translate("MainWindow", "CS&C 09"))
        self.close_spread_box.setItemText(8, _translate("MainWindow", "Y/M 05"))
        self.close_spread_box.setItemText(9, _translate("MainWindow", "OI/RM 05"))
        self.term_box.setItemText(0, _translate("MainWindow", "M"))
        self.term_box.setItemText(1, _translate("MainWindow", "RM"))
        self.term_box.setItemText(2, _translate("MainWindow", "P"))
        self.term_box.setItemText(3, _translate("MainWindow", "Y"))
        self.term_box.setItemText(4, _translate("MainWindow", "OI"))
        self.term_box.setItemText(5, _translate("MainWindow", "C"))
        self.term_box.setItemText(6, _translate("MainWindow", "CS"))
        self.m_box.setItemText(0, _translate("MainWindow", "M15"))
        self.m_box.setItemText(1, _translate("MainWindow", "M59"))
        self.m_box.setItemText(2, _translate("MainWindow", "M91"))
        self.m_box.setItemText(3, _translate("MainWindow", "RM15"))
        self.m_box.setItemText(4, _translate("MainWindow", "RM59"))
        self.m_box.setItemText(5, _translate("MainWindow", "RM91"))
        self.m_box.setItemText(6, _translate("MainWindow", "Y15"))
        self.m_box.setItemText(7, _translate("MainWindow", "Y59"))
        self.m_box.setItemText(8, _translate("MainWindow", "Y91"))
        self.m_box.setItemText(9, _translate("MainWindow", "P15"))
        self.m_box.setItemText(10, _translate("MainWindow", "P59"))
        self.m_box.setItemText(11, _translate("MainWindow", "P91"))
        self.m_box.setItemText(12, _translate("MainWindow", "OI15"))
        self.m_box.setItemText(13, _translate("MainWindow", "OI95"))
        self.m_box.setItemText(14, _translate("MainWindow", "OI91"))
        self.m_box.setItemText(15, _translate("MainWindow", "C15"))
        self.m_box.setItemText(16, _translate("MainWindow", "C59"))
        self.m_box.setItemText(17, _translate("MainWindow", "C91"))
        self.m_box.setItemText(18, _translate("MainWindow", "CS15"))
        self.m_box.setItemText(19, _translate("MainWindow", "CS59"))
        self.m_box.setItemText(20, _translate("MainWindow", "CS91"))
        self.axis_box.setItemText(0, _translate("MainWindow", "图1"))
        self.axis_box.setItemText(1, _translate("MainWindow", "图2"))
        self.axis_box.setItemText(2, _translate("MainWindow", "图3"))
        self.axis_box.setItemText(3, _translate("MainWindow", "图4"))
        self.b_n_box.setCurrentText(_translate("MainWindow", "60"))
        self.b_n_box.setItemText(0, _translate("MainWindow", "40"))
        self.b_n_box.setItemText(1, _translate("MainWindow", "60"))
        self.b_n_box.setItemText(2, _translate("MainWindow", "70"))
        self.b_n_box.setItemText(3, _translate("MainWindow", "80"))
        self.b_n_box.setItemText(4, _translate("MainWindow", "100"))
        self.b_n0_box.setCurrentText(_translate("MainWindow", "20"))
        self.b_n0_box.setItemText(0, _translate("MainWindow", "10"))
        self.b_n0_box.setItemText(1, _translate("MainWindow", "20"))
        self.b_n0_box.setItemText(2, _translate("MainWindow", "30"))
        self.b_n0_box.setItemText(3, _translate("MainWindow", "40"))
        self.vol_code.setItemText(0, _translate("MainWindow", "M.DCE"))
        self.vol_code.setItemText(1, _translate("MainWindow", "M05M.DCE"))
        self.vol_code.setItemText(2, _translate("MainWindow", "M09M.DCE"))
        self.vol_code.setItemText(3, _translate("MainWindow", "RM.CZC"))
        self.vol_code.setItemText(4, _translate("MainWindow", "RM05.CZC"))
        self.vol_code.setItemText(5, _translate("MainWindow", "RM09.CZC"))
        self.vol_code.setItemText(6, _translate("MainWindow", "Y.DCE"))
        self.vol_code.setItemText(7, _translate("MainWindow", "Y05M.DCE"))
        self.vol_code.setItemText(8, _translate("MainWindow", "Y09M.DCE"))
        self.vol_code.setItemText(9, _translate("MainWindow", "P.DCE"))
        self.vol_code.setItemText(10, _translate("MainWindow", "P05M.DCE"))
        self.vol_code.setItemText(11, _translate("MainWindow", "P09M.DCE"))
        self.vol_code.setItemText(12, _translate("MainWindow", "OI.CZC"))
        self.vol_code.setItemText(13, _translate("MainWindow", "OI05M.CZC"))
        self.vol_code.setItemText(14, _translate("MainWindow", "OI09M.CZC"))
        self.vol_code.setItemText(15, _translate("MainWindow", "C.DCE"))
        self.vol_code.setItemText(16, _translate("MainWindow", "C03M.DCE"))
        self.vol_code.setItemText(17, _translate("MainWindow", "C05M.DCE"))
        self.vol_code.setItemText(18, _translate("MainWindow", "C07M.DCE"))
        self.vol_code.setItemText(19, _translate("MainWindow", "CS.DCE"))
        self.vol_code.setItemText(20, _translate("MainWindow", "CS03M.DCE"))
        self.vol_code.setItemText(21, _translate("MainWindow", "CS05M.DCE"))
        self.vol_code.setItemText(22, _translate("MainWindow", "CS07M.DCE"))
        self.vol_code.setItemText(23, _translate("MainWindow", "CF.CZC"))
        self.vol_code.setItemText(24, _translate("MainWindow", "CF05M.CZC"))
        self.vol_code.setItemText(25, _translate("MainWindow", "CF09M.CZC"))
        self.vol_code.setItemText(26, _translate("MainWindow", "SR.CZC"))
        self.vol_code.setItemText(27, _translate("MainWindow", "SR05M.CZC"))
        self.vol_code.setItemText(28, _translate("MainWindow", "SR09M.CZC"))
        self.w_box.setItemText(0, _translate("MainWindow", "22"))
        self.w_box.setItemText(1, _translate("MainWindow", "30"))
        self.w_box.setItemText(2, _translate("MainWindow", "40"))
        self.w_box.setItemText(3, _translate("MainWindow", "60"))
        self.w_box.setItemText(4, _translate("MainWindow", "90"))
        self.w_box.setItemText(5, _translate("MainWindow", "120"))
        self.label_9.setText(_translate("MainWindow", "合约代码"))
        self.label_11.setText(_translate("MainWindow", "       时间"))
        self.label_6.setText(_translate("MainWindow", "Position"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "MainPage"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "统计信息"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1-点链接：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">弹出wind登陆界面</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2-链接成功后弹出对话框</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3-改动日期需要再点一次链接取数</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">（取数没成功不会出图）</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4-图位置参数</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">作用于全部季节性图表</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5-n&amp;n0参数</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">作用于非期限结构以外全部图表</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">n = 过去的多少天（坐标轴上负数表示）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">n0 = 未来的多少天（坐标轴上正数表示）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">日期 → n = 0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">日期 = 格式有误的情况下自动取当天的日期</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">（所有显示的日期均为交易日）</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">***** 波动率季节性每点一次 单独调取一次 数据与其它图表数据独立</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">***** 日期格式不正确会自动调用当天日期</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">界面UI用自PyQt5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">数据来源：Wind</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "备注"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
